### ISSUE TITLE
Unable to cache bundle: mvn:org.ogema.ref-impl/permission-admin/2.0.1

### ISSUE THREAD

**Issue by kuch3n** [ogema/ogema#1]
Hi,

"mvn install" fails with a:
Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project ogema-exam-base: There are test failures.

Log: http://nopaste.info/b360b43366.html
Error Files / Steps to reproduce: http://nopaste.info/57c0e68a5c.html

**Comment by kuch3n** [comment]
resolved with:
mvn install -DskipTests 
mvn install

**Comment by TimoFischer** [comment]
Thanks for pointing this out. This is a known behavior (not really wanting to call it an "issue" because I don't really consider it an issue). We will add a README file in the next release to clarify this. The recommended build command indeed is the above or alternatively

mvn clean install -DskipTests
mvn test

As an explanation of why you have to do a full build without test before running the tests: The tests performed are, in a sense, integration tests. The test environment, based on Pax Exam, starts up an OGEMA and OSGi framework and then usually runs as an OGEMA application that performs tests. To do so, all OGEMA bundles must be available, i.e. they must have been built before that point. I would not know how to tell Maven to first build everything and then run the tests (except for explicitly typing in the two commands "install" and "test" in two separate commands). Technically, we could probably put the tests into separate projects to have the code compile in one go. But having the tests close to the sources has its charm. So I currently think we will keep it as is.

Note that for running OGEMA (e.g. the demokit) or for developing an OGEMA application it is not needed to compile the source code yourself. Both the OGEMA Launcher and the seed-pom for new applications (cf. https://www.ogema-source.net/wiki/display/OGEMA/Creating+a+new+Application) can automatically download the required jars (provided you are connected to the Internet).
